-- WAHY LAB SOLUTIONS: TECHNOLOGICAL SKILL GAP PROJECT
-- Complete MySQL script: table + 100 INSERT records + analysis queries
CREATE DATABASE IF NOT EXISTS wahy_skill_gap;
USE wahy_skill_gap;

DROP TABLE IF EXISTS Wahy_Employee_Skill_Gap;
CREATE TABLE Wahy_Employee_Skill_Gap (
    `Respondent_ID` VARCHAR(10) PRIMARY KEY,
    `Age` VARCHAR(30),
    `Gender` TEXT,
    `Designation` TEXT,
    `Department` TEXT,
    `Association_with_Wahy` TEXT,
    `Q6_Technical_skills_required` TEXT,
    `Q7_Adapt_to_new_technologies` TEXT,
    `Q8_Adequate_technical_training` TEXT,
    `Q9_Mentor_technical_guidance` TEXT,
    `Q10_Opportunities_to_improve_skills` TEXT,
    `Q11_Confidence_using_software_tools` TEXT,
    `Q12_Need_additional_technical_training` TEXT,
    `Q13_Training_applies_knowledge_to_real_projects` TEXT,
    `Q14_Complete_tasks_on_time` TEXT,
    `Q15_Work_quality_meets_expectations` TEXT,
    `Q16_Solve_technical_problems_independently` TEXT,
    `Q17_Collaborate_effectively` TEXT,
    `Q18_Adapt_to_project_changes` TEXT,
    `Q19_Technical_skills_influence_performance` TEXT,
    `Q20_Training_improved_performance` TEXT,
    `Q21_Satisfaction_with_work_performance` TEXT,
    `Q22_Current_technologies` TEXT,
    `Q23_Additional_training_needed` TEXT,
    `Q24_Most_effective_learning_method` TEXT,
    `Q25_Satisfaction_with_Wahy_training` TEXT,
    `Q26_Challenges` TEXT,
    `Q27_Suggestions` TEXT
);

-- INSERT RECORDS 1 TO 20
INSERT INTO Wahy_Employee_Skill_Gap (`Respondent_ID`, `Age`, `Gender`, `Designation`, `Department`, `Association_with_Wahy`, `Q6_Technical_skills_required`, `Q7_Adapt_to_new_technologies`, `Q8_Adequate_technical_training`, `Q9_Mentor_technical_guidance`, `Q10_Opportunities_to_improve_skills`, `Q11_Confidence_using_software_tools`, `Q12_Need_additional_technical_training`, `Q13_Training_applies_knowledge_to_real_projects`, `Q14_Complete_tasks_on_time`, `Q15_Work_quality_meets_expectations`, `Q16_Solve_technical_problems_independently`, `Q17_Collaborate_effectively`, `Q18_Adapt_to_project_changes`, `Q19_Technical_skills_influence_performance`, `Q20_Training_improved_performance`, `Q21_Satisfaction_with_work_performance`, `Q22_Current_technologies`, `Q23_Additional_training_needed`, `Q24_Most_effective_learning_method`, `Q25_Satisfaction_with_Wahy_training`, `Q26_Challenges`, `Q27_Suggestions`) VALUES
('R001', '20–25 years', 'Male', 'Intern', 'Data Analytics', 'Less than 3 months', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Power BI; Python; SQL', 'SQL; Business Analytics; Python', 'Classroom Training', 'Satisfied', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.'),
('R002', '20–25 years', 'Female', 'Intern', 'Software Testing', 'Less than 3 months', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Neutral', 'SQL; Software Testing', 'Power BI; Data Analytics', 'Mentor Guidance', 'Dissatisfied', 'Limited time to learn new technologies alongside assigned work.', 'Create structured learning paths for each department.'),
('R003', '20–25 years', 'Male', 'Intern', 'Other', '3–6 months', 'Disagree', 'Neutral', 'Strongly disagree', 'Disagree', 'Neutral', 'Disagree', 'Strongly agree', 'Neutral', 'Agree', 'Neutral', 'Disagree', 'Disagree', 'Disagree', 'Neutral', 'Disagree', 'Disagree', 'SQL; Business Analytics', 'Power BI; Python', 'Live Projects', 'Neutral', 'Need more hands-on practice with new tools.', 'Provide more hands-on projects and practical workshops.'),
('R004', '20–25 years', 'Male', 'Intern', 'Software Testing', '3–6 months', 'Neutral', 'Disagree', 'Neutral', 'Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Disagree', 'Python; SQL', 'Business Analytics; Data Analytics; Power BI', 'Mentor Guidance', 'Very satisfied', 'More real-project exposure would improve confidence.', 'Increase mentor guidance and technical review sessions.'),
('R005', '20–25 years', 'Male', 'Intern', 'Other', '3–6 months', 'Agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Data Analytics; Business Analytics', 'SQL; Python', 'Classroom Training', 'Neutral', 'Keeping up with multiple technologies is challenging.', 'Offer regular sessions on new technologies.'),
('R006', '20–25 years', 'Male', 'Intern', 'Business Analytics', 'Less than 3 months', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Strongly agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Disagree', 'Power BI; SQL; Data Analytics', 'Business Analytics; Data Analytics; Power BI', 'Live Projects', 'Neutral', 'Some tools are difficult without practical examples.', 'Offer regular sessions on new technologies.'),
('R007', '20–25 years', 'Prefer not to say', 'Intern', 'Business Analytics', 'Less than 3 months', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Strongly agree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Strongly agree', 'Agree', 'Agree', 'Disagree', 'Agree', 'Data Analytics; Python', 'SQL; Power BI; Data Analytics', 'Classroom Training', 'Satisfied', 'Need more hands-on practice with new tools.', 'Provide more real-world project exposure.'),
('R008', '26–30 years', 'Female', 'Intern', 'Data Analytics', '3–6 months', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'SQL; Data Analytics', 'Business Analytics; SQL', 'Online Courses', 'Neutral', 'More real-project exposure would improve confidence.', 'Provide more hands-on projects and practical workshops.'),
('R009', '20–25 years', 'Male', 'Intern', 'Data Analytics', 'Less than 3 months', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Python; Data Analytics; Power BI', 'Business Analytics; Power BI', 'Mentor Guidance', 'Neutral', 'Keeping up with multiple technologies is challenging.', 'Provide more hands-on projects and practical workshops.'),
('R010', '20–25 years', 'Female', 'Intern', 'UI/UX Design', 'Less than 3 months', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Strongly agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'UI/UX Design; JavaScript', 'UI/UX Design; Data Analytics', 'Self-Learning', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Create structured learning paths for each department.'),
('R011', '20–25 years', 'Male', 'Intern', 'Data Analytics', '3–6 months', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Disagree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'SQL; Python; Business Analytics', 'Data Analytics; SQL', 'Mentor Guidance', 'Dissatisfied', 'Some tools are difficult without practical examples.', 'Increase mentor guidance and technical review sessions.'),
('R012', '26–30 years', 'Male', 'Intern', 'Data Analytics', '3–6 months', 'Neutral', 'Agree', 'Agree', 'Agree', 'Disagree', 'Neutral', 'Agree', 'Disagree', 'Agree', 'Disagree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Power BI; Business Analytics; Python', 'Data Analytics; Python', 'Online Courses', 'Neutral', 'Need more guidance on unfamiliar technical tasks.', 'Provide more hands-on projects and practical workshops.'),
('R013', 'Below 20 years', 'Female', 'Intern', 'Mobile App Development', '3–6 months', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Strongly agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'SQL; Java', 'Python; SQL', 'Self-Learning', 'Neutral', 'Limited time to learn new technologies alongside assigned work.', 'Provide more real-world project exposure.'),
('R014', '20–25 years', 'Male', 'Intern', 'Web Development', '3–6 months', 'Disagree', 'Neutral', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Neutral', 'Disagree', 'SQL; React JS; HTML/CSS', 'Business Analytics; SQL; JavaScript', 'Live Projects', 'Satisfied', 'Limited time to learn new technologies alongside assigned work.', 'Offer regular sessions on new technologies.'),
('R015', '26–30 years', 'Female', 'Intern', 'Human Resources', '3–6 months', 'Agree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Disagree', 'Neutral', 'SQL; Data Analytics; Python', 'Python; SQL', 'Classroom Training', 'Neutral', 'Keeping up with multiple technologies is challenging.', 'Increase mentor guidance and technical review sessions.'),
('R016', '20–25 years', 'Female', 'Intern', 'Data Analytics', 'Less than 3 months', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Disagree', 'Agree', 'Agree', 'Neutral', 'Power BI; Data Analytics; Python', 'Data Analytics; Python', 'Online Courses', 'Neutral', 'Need more guidance on unfamiliar technical tasks.', 'Provide more real-world project exposure.'),
('R017', 'Below 20 years', 'Male', 'Intern', 'Software Testing', 'Less than 3 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Neutral', 'SQL; Python; Java', 'Data Analytics; Power BI', 'Mentor Guidance', 'Very dissatisfied', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.'),
('R018', '20–25 years', 'Female', 'Intern', 'Software Testing', '3–6 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'SQL; Java; Python', 'Python; Data Analytics', 'Self-Learning', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Offer regular sessions on new technologies.'),
('R019', '26–30 years', 'Female', 'Intern', 'Mobile App Development', 'Less than 3 months', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Disagree', 'Strongly agree', 'Disagree', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Disagree', 'Neutral', 'JavaScript; SQL; Java', 'JavaScript; Data Analytics; Flutter', 'Mentor Guidance', 'Satisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more real-world project exposure.'),
('R020', '20–25 years', 'Male', 'Intern', 'Software Testing', 'Less than 3 months', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Disagree', 'Disagree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'SQL; Java', 'SQL; Data Analytics', 'Online Courses', 'Satisfied', 'More real-project exposure would improve confidence.', 'Conduct short training sessions on required tools.');

-- INSERT RECORDS 21 TO 40
INSERT INTO Wahy_Employee_Skill_Gap (`Respondent_ID`, `Age`, `Gender`, `Designation`, `Department`, `Association_with_Wahy`, `Q6_Technical_skills_required`, `Q7_Adapt_to_new_technologies`, `Q8_Adequate_technical_training`, `Q9_Mentor_technical_guidance`, `Q10_Opportunities_to_improve_skills`, `Q11_Confidence_using_software_tools`, `Q12_Need_additional_technical_training`, `Q13_Training_applies_knowledge_to_real_projects`, `Q14_Complete_tasks_on_time`, `Q15_Work_quality_meets_expectations`, `Q16_Solve_technical_problems_independently`, `Q17_Collaborate_effectively`, `Q18_Adapt_to_project_changes`, `Q19_Technical_skills_influence_performance`, `Q20_Training_improved_performance`, `Q21_Satisfaction_with_work_performance`, `Q22_Current_technologies`, `Q23_Additional_training_needed`, `Q24_Most_effective_learning_method`, `Q25_Satisfaction_with_Wahy_training`, `Q26_Challenges`, `Q27_Suggestions`) VALUES
('R021', '20–25 years', 'Male', 'Intern', 'Other', '3–6 months', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Disagree', 'Neutral', 'SQL; Data Analytics', 'SQL; Business Analytics', 'Classroom Training', 'Satisfied', 'Need more hands-on practice with new tools.', 'Create structured learning paths for each department.'),
('R022', '20–25 years', 'Male', 'Intern', 'Digital Marketing', 'Less than 3 months', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Data Analytics; Digital Marketing; Business Analytics', 'Data Analytics; Python; SQL', 'Self-Learning', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Create structured learning paths for each department.'),
('R023', 'Below 20 years', 'Female', 'Intern', 'Business Analytics', '3–6 months', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Data Analytics; SQL', 'Power BI; Business Analytics', 'Live Projects', 'Satisfied', 'Limited time to learn new technologies alongside assigned work.', 'Provide more hands-on projects and practical workshops.'),
('R024', '20–25 years', 'Male', 'Intern', 'UI/UX Design', '3–6 months', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Strongly agree', 'JavaScript; UI/UX Design; HTML/CSS', 'Python; HTML/CSS; Business Analytics', 'Online Courses', 'Neutral', 'Some tools are difficult without practical examples.', 'Offer regular sessions on new technologies.'),
('R025', '26–30 years', 'Male', 'Intern', 'Web Development', 'Less than 3 months', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'SQL; React JS; JavaScript', 'SQL; React JS', 'Classroom Training', 'Dissatisfied', 'More real-project exposure would improve confidence.', 'Increase mentor guidance and technical review sessions.'),
('R026', '20–25 years', 'Female', 'Intern', 'Business Analytics', '6–12 months', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Data Analytics; Power BI', 'SQL; Business Analytics', 'Self-Learning', 'Neutral', 'Some tools are difficult without practical examples.', 'Conduct short training sessions on required tools.'),
('R027', '20–25 years', 'Male', 'Intern', 'Software Testing', '3–6 months', 'Disagree', 'Neutral', 'Disagree', 'Disagree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Disagree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Software Testing; SQL; Python', 'Python; Java; Power BI', 'Live Projects', 'Neutral', 'More real-project exposure would improve confidence.', 'Conduct short training sessions on required tools.'),
('R028', '26–30 years', 'Male', 'Intern', 'Web Development', 'Less than 3 months', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Disagree', 'Agree', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'JavaScript; React JS', 'SQL; Power BI; HTML/CSS', 'Live Projects', 'Neutral', 'Some tools are difficult without practical examples.', 'Provide more hands-on projects and practical workshops.'),
('R029', '20–25 years', 'Female', 'Intern', 'Human Resources', 'Less than 3 months', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'SQL; Business Analytics; Python', 'Power BI; Python; SQL', 'Classroom Training', 'Dissatisfied', 'Some tools are difficult without practical examples.', 'Offer regular sessions on new technologies.'),
('R030', '20–25 years', 'Male', 'Intern', 'Other', '3–6 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Business Analytics; Data Analytics', 'Business Analytics; Power BI', 'Live Projects', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more real-world project exposure.'),
('R031', '20–25 years', 'Female', 'Intern', 'Business Analytics', 'Less than 3 months', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Python; Business Analytics; SQL', 'SQL; Business Analytics; Data Analytics', 'Classroom Training', 'Very dissatisfied', 'Need more hands-on practice with new tools.', 'Provide more real-world project exposure.'),
('R032', '20–25 years', 'Female', 'Intern', 'Mobile App Development', '3–6 months', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'SQL; Java', 'SQL; JavaScript; Power BI', 'Self-Learning', 'Dissatisfied', 'Need more hands-on practice with new tools.', 'Provide more real-world project exposure.'),
('R033', '20–25 years', 'Female', 'Intern', 'Business Analytics', 'Less than 3 months', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Strongly disagree', 'Disagree', 'Strongly agree', 'Disagree', 'Disagree', 'Neutral', 'Neutral', 'Strongly disagree', 'Disagree', 'Disagree', 'Strongly disagree', 'Neutral', 'SQL; Python', 'Python; Power BI', 'Mentor Guidance', 'Satisfied', 'Limited time to learn new technologies alongside assigned work.', 'Conduct short training sessions on required tools.'),
('R034', '26–30 years', 'Male', 'Intern', 'Data Analytics', '6–12 months', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'SQL; Python; Power BI', 'Data Analytics; SQL; Business Analytics', 'Online Courses', 'Very dissatisfied', 'Some tools are difficult without practical examples.', 'Provide more real-world project exposure.'),
('R035', '20–25 years', 'Male', 'Intern', 'Human Resources', 'Less than 3 months', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Business Analytics; Data Analytics; Python', 'SQL; Business Analytics; Data Analytics', 'Classroom Training', 'Dissatisfied', 'Some tools are difficult without practical examples.', 'Conduct short training sessions on required tools.'),
('R036', '20–25 years', 'Male', 'Intern', 'Human Resources', 'Less than 3 months', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Neutral', 'SQL; Data Analytics', 'Python; Power BI', 'Self-Learning', 'Neutral', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.'),
('R037', '20–25 years', 'Male', 'Intern', 'Mobile App Development', '3–6 months', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Neutral', 'Strongly agree', 'Neutral', 'Strongly disagree', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'JavaScript; Java', 'Power BI; SQL', 'Self-Learning', 'Satisfied', 'Keeping up with multiple technologies is challenging.', 'Conduct short training sessions on required tools.'),
('R038', '20–25 years', 'Female', 'Intern', 'Business Analytics', '3–6 months', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Strongly agree', 'Agree', 'SQL; Business Analytics', 'SQL; Data Analytics', 'Mentor Guidance', 'Neutral', 'Keeping up with multiple technologies is challenging.', 'Provide more real-world project exposure.'),
('R039', '20–25 years', 'Male', 'Intern', 'Data Analytics', '3–6 months', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Agree', 'Agree', 'Disagree', 'SQL; Data Analytics; Business Analytics', 'Data Analytics; Business Analytics', 'Online Courses', 'Neutral', 'More real-project exposure would improve confidence.', 'Provide more hands-on projects and practical workshops.'),
('R040', '26–30 years', 'Female', 'Intern', 'Data Analytics', '3–6 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Agree', 'SQL; Power BI; Data Analytics', 'SQL; Data Analytics; Python', 'Classroom Training', 'Dissatisfied', 'Keeping up with multiple technologies is challenging.', 'Conduct short training sessions on required tools.');

-- INSERT RECORDS 41 TO 60
INSERT INTO Wahy_Employee_Skill_Gap (`Respondent_ID`, `Age`, `Gender`, `Designation`, `Department`, `Association_with_Wahy`, `Q6_Technical_skills_required`, `Q7_Adapt_to_new_technologies`, `Q8_Adequate_technical_training`, `Q9_Mentor_technical_guidance`, `Q10_Opportunities_to_improve_skills`, `Q11_Confidence_using_software_tools`, `Q12_Need_additional_technical_training`, `Q13_Training_applies_knowledge_to_real_projects`, `Q14_Complete_tasks_on_time`, `Q15_Work_quality_meets_expectations`, `Q16_Solve_technical_problems_independently`, `Q17_Collaborate_effectively`, `Q18_Adapt_to_project_changes`, `Q19_Technical_skills_influence_performance`, `Q20_Training_improved_performance`, `Q21_Satisfaction_with_work_performance`, `Q22_Current_technologies`, `Q23_Additional_training_needed`, `Q24_Most_effective_learning_method`, `Q25_Satisfaction_with_Wahy_training`, `Q26_Challenges`, `Q27_Suggestions`) VALUES
('R041', '20–25 years', 'Male', 'Intern', 'Business Analytics', 'Less than 3 months', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Strongly agree', 'Neutral', 'SQL; Business Analytics; Data Analytics', 'Python; Power BI', 'Online Courses', 'Dissatisfied', 'Need more hands-on practice with new tools.', 'Increase mentor guidance and technical review sessions.'),
('R042', 'Above 30 years', 'Male', 'Intern', 'Mobile App Development', 'Less than 3 months', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'JavaScript; Flutter; SQL', 'Data Analytics; Power BI; SQL', 'Self-Learning', 'Neutral', 'Limited time to learn new technologies alongside assigned work.', 'Offer regular sessions on new technologies.'),
('R043', '20–25 years', 'Female', 'Intern', 'Web Development', 'Less than 3 months', 'Agree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree', 'Neutral', 'Strongly agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'SQL; React JS', 'Power BI; Business Analytics; Data Analytics', 'Self-Learning', 'Dissatisfied', 'Limited time to learn new technologies alongside assigned work.', 'Provide more real-world project exposure.'),
('R044', '20–25 years', 'Female', 'Intern', 'Web Development', 'Less than 3 months', 'Agree', 'Disagree', 'Neutral', 'Disagree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'SQL; JavaScript', 'Python; SQL', 'Online Courses', 'Satisfied', 'More real-project exposure would improve confidence.', 'Increase mentor guidance and technical review sessions.'),
('R045', '20–25 years', 'Female', 'Intern', 'Digital Marketing', '3–6 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'SQL; Data Analytics', 'Python; Power BI', 'Live Projects', 'Dissatisfied', 'More real-project exposure would improve confidence.', 'Provide more real-world project exposure.'),
('R046', '20–25 years', 'Male', 'Intern', 'Business Analytics', 'Less than 3 months', 'Disagree', 'Agree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Agree', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Disagree', 'SQL; Python', 'Business Analytics; Python; Data Analytics', 'Live Projects', 'Dissatisfied', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.'),
('R047', '20–25 years', 'Female', 'Intern', 'Mobile App Development', '3–6 months', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'JavaScript; SQL; Java', 'Flutter; Data Analytics; Power BI', 'Classroom Training', 'Neutral', 'Limited time to learn new technologies alongside assigned work.', 'Conduct short training sessions on required tools.'),
('R048', '26–30 years', 'Male', 'Intern', 'Software Testing', 'Less than 3 months', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'SQL; Java; Software Testing', 'Java; Data Analytics; Software Testing', 'Live Projects', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more real-world project exposure.'),
('R049', '20–25 years', 'Female', 'Intern', 'Mobile App Development', 'Less than 3 months', 'Disagree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'SQL; Java', 'SQL; Python', 'Classroom Training', 'Neutral', 'Need more guidance on unfamiliar technical tasks.', 'Provide more real-world project exposure.'),
('R050', '20–25 years', 'Male', 'Intern', 'Business Analytics', '3–6 months', 'Neutral', 'Disagree', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Business Analytics; SQL; Python', 'Business Analytics; Power BI; Python', 'Mentor Guidance', 'Satisfied', 'Keeping up with multiple technologies is challenging.', 'Offer regular sessions on new technologies.'),
('R051', '26–30 years', 'Male', 'Employee', 'Data Analytics', '3–6 months', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Strongly agree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Agree', 'Agree', 'Neutral', 'Python; Business Analytics; SQL', 'Business Analytics; SQL; Data Analytics', 'Classroom Training', 'Neutral', 'More real-project exposure would improve confidence.', 'Increase mentor guidance and technical review sessions.'),
('R052', '20–25 years', 'Female', 'Employee', 'Data Analytics', 'More than 1 year', 'Agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Neutral', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'SQL; Business Analytics', 'Python; Data Analytics; Power BI', 'Online Courses', 'Dissatisfied', 'Keeping up with multiple technologies is challenging.', 'Provide more hands-on projects and practical workshops.'),
('R053', '26–30 years', 'Male', 'Team Leader', 'Data Analytics', '6–12 months', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Neutral', 'Strongly agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Power BI; Data Analytics', 'Python; SQL', 'Online Courses', 'Very dissatisfied', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.'),
('R054', '26–30 years', 'Female', 'Team Leader', 'Human Resources', 'More than 1 year', 'Agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Disagree', 'Strongly agree', 'Strongly agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Python; Business Analytics; Data Analytics', 'Data Analytics; Python; SQL', 'Classroom Training', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more real-world project exposure.'),
('R055', '20–25 years', 'Male', 'Employee', 'Web Development', '6–12 months', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Disagree', 'Agree', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'SQL; HTML/CSS; React JS', 'Power BI; JavaScript; SQL', 'Classroom Training', 'Neutral', 'More real-project exposure would improve confidence.', 'Offer regular sessions on new technologies.'),
('R056', '26–30 years', 'Male', 'Employee', 'Web Development', 'More than 1 year', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'JavaScript; React JS; HTML/CSS', 'JavaScript; Business Analytics', 'Classroom Training', 'Dissatisfied', 'Need more hands-on practice with new tools.', 'Provide more real-world project exposure.'),
('R057', '26–30 years', 'Male', 'Employee', 'Web Development', 'More than 1 year', 'Neutral', 'Disagree', 'Strongly disagree', 'Disagree', 'Disagree', 'Neutral', 'Strongly agree', 'Strongly disagree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Disagree', 'Neutral', 'Strongly disagree', 'Neutral', 'JavaScript; HTML/CSS; SQL', 'SQL; React JS; Data Analytics', 'Online Courses', 'Very satisfied', 'Keeping up with multiple technologies is challenging.', 'Increase mentor guidance and technical review sessions.'),
('R058', '20–25 years', 'Female', 'Employee', 'UI/UX Design', '6–12 months', 'Strongly agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Neutral', 'Strongly agree', 'Disagree', 'Agree', 'Strongly agree', 'Agree', 'Strongly agree', 'Agree', 'Strongly agree', 'Agree', 'Strongly agree', 'Strongly agree', 'UI/UX Design; JavaScript', 'UI/UX Design; Power BI', 'Mentor Guidance', 'Dissatisfied', 'More real-project exposure would improve confidence.', 'Increase mentor guidance and technical review sessions.'),
('R059', '26–30 years', 'Female', 'Employee', 'Business Analytics', 'More than 1 year', 'Agree', 'Strongly agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Neutral', 'Agree', 'Strongly agree', 'Data Analytics; Power BI', 'Data Analytics; Python', 'Classroom Training', 'Dissatisfied', 'Limited time to learn new technologies alongside assigned work.', 'Offer regular sessions on new technologies.'),
('R060', '20–25 years', 'Male', 'Team Leader', 'Business Analytics', 'More than 1 year', 'Strongly agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Data Analytics; Business Analytics; SQL', 'SQL; Power BI; Python', 'Mentor Guidance', 'Neutral', 'Some tools are difficult without practical examples.', 'Conduct short training sessions on required tools.');

-- INSERT RECORDS 61 TO 80
INSERT INTO Wahy_Employee_Skill_Gap (`Respondent_ID`, `Age`, `Gender`, `Designation`, `Department`, `Association_with_Wahy`, `Q6_Technical_skills_required`, `Q7_Adapt_to_new_technologies`, `Q8_Adequate_technical_training`, `Q9_Mentor_technical_guidance`, `Q10_Opportunities_to_improve_skills`, `Q11_Confidence_using_software_tools`, `Q12_Need_additional_technical_training`, `Q13_Training_applies_knowledge_to_real_projects`, `Q14_Complete_tasks_on_time`, `Q15_Work_quality_meets_expectations`, `Q16_Solve_technical_problems_independently`, `Q17_Collaborate_effectively`, `Q18_Adapt_to_project_changes`, `Q19_Technical_skills_influence_performance`, `Q20_Training_improved_performance`, `Q21_Satisfaction_with_work_performance`, `Q22_Current_technologies`, `Q23_Additional_training_needed`, `Q24_Most_effective_learning_method`, `Q25_Satisfaction_with_Wahy_training`, `Q26_Challenges`, `Q27_Suggestions`) VALUES
('R061', '26–30 years', 'Male', 'Employee', 'Data Analytics', '6–12 months', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Disagree', 'Disagree', 'Agree', 'Disagree', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Python; Data Analytics; Power BI', 'Data Analytics; Business Analytics; Power BI', 'Mentor Guidance', 'Dissatisfied', 'Keeping up with multiple technologies is challenging.', 'Increase mentor guidance and technical review sessions.'),
('R062', '26–30 years', 'Female', 'Employee', 'Web Development', 'More than 1 year', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'SQL; React JS', 'HTML/CSS; SQL; React JS', 'Mentor Guidance', 'Neutral', 'Need more hands-on practice with new tools.', 'Offer regular sessions on new technologies.'),
('R063', '20–25 years', 'Male', 'Employee', 'Business Analytics', 'More than 1 year', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Disagree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Strongly agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'SQL; Power BI; Business Analytics', 'Python; Power BI; Business Analytics', 'Live Projects', 'Neutral', 'Limited time to learn new technologies alongside assigned work.', 'Provide more hands-on projects and practical workshops.'),
('R064', '26–30 years', 'Female', 'Manager', 'Web Development', '6–12 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'SQL; JavaScript', 'SQL; Data Analytics', 'Self-Learning', 'Neutral', 'Need more hands-on practice with new tools.', 'Increase mentor guidance and technical review sessions.'),
('R065', '20–25 years', 'Female', 'Manager', 'Mobile App Development', 'More than 1 year', 'Neutral', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'JavaScript; Java; Flutter', 'Data Analytics; Java; Python', 'Mentor Guidance', 'Dissatisfied', 'Some tools are difficult without practical examples.', 'Increase mentor guidance and technical review sessions.'),
('R066', '26–30 years', 'Female', 'Employee', 'Human Resources', 'More than 1 year', 'Agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Disagree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Data Analytics; Business Analytics', 'Python; Business Analytics; SQL', 'Live Projects', 'Dissatisfied', 'Limited time to learn new technologies alongside assigned work.', 'Offer regular sessions on new technologies.'),
('R067', '26–30 years', 'Female', 'Employee', 'Software Testing', 'More than 1 year', 'Neutral', 'Neutral', 'Agree', 'Disagree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Python; Java', 'SQL; Java; Data Analytics', 'Online Courses', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Increase mentor guidance and technical review sessions.'),
('R068', '20–25 years', 'Male', 'Employee', 'Human Resources', '6–12 months', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Strongly agree', 'Disagree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Data Analytics; Business Analytics', 'Business Analytics; Data Analytics', 'Self-Learning', 'Neutral', 'Need more hands-on practice with new tools.', 'Increase mentor guidance and technical review sessions.'),
('R069', '20–25 years', 'Male', 'Employee', 'Human Resources', 'More than 1 year', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Data Analytics; Python; Business Analytics', 'SQL; Power BI; Python', 'Mentor Guidance', 'Neutral', 'Limited time to learn new technologies alongside assigned work.', 'Offer regular sessions on new technologies.'),
('R070', '26–30 years', 'Male', 'Employee', 'Other', 'More than 1 year', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Strongly agree', 'Neutral', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Strongly agree', 'Neutral', 'Agree', 'Strongly agree', 'Agree', 'Business Analytics; Data Analytics', 'Power BI; Business Analytics; Python', 'Mentor Guidance', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more hands-on projects and practical workshops.'),
('R071', '26–30 years', 'Female', 'Employee', 'Web Development', '3–6 months', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'React JS; HTML/CSS; JavaScript', 'Business Analytics; JavaScript; React JS', 'Online Courses', 'Satisfied', 'More real-project exposure would improve confidence.', 'Provide more real-world project exposure.'),
('R072', '26–30 years', 'Male', 'Employee', 'UI/UX Design', '6–12 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Strongly agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'HTML/CSS; UI/UX Design', 'Data Analytics; UI/UX Design; JavaScript', 'Live Projects', 'Dissatisfied', 'Some tools are difficult without practical examples.', 'Provide more real-world project exposure.'),
('R073', '26–30 years', 'Prefer not to say', 'Employee', 'Data Analytics', 'More than 1 year', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Power BI; Data Analytics; Python', 'Business Analytics; Python; Data Analytics', 'Mentor Guidance', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Create structured learning paths for each department.'),
('R074', '20–25 years', 'Male', 'Employee', 'Data Analytics', 'More than 1 year', 'Disagree', 'Neutral', 'Disagree', 'Disagree', 'Neutral', 'Disagree', 'Strongly agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Data Analytics; Business Analytics', 'Power BI; Python', 'Mentor Guidance', 'Satisfied', 'Need more guidance on unfamiliar technical tasks.', 'Offer regular sessions on new technologies.'),
('R075', '26–30 years', 'Male', 'Employee', 'Other', '6–12 months', 'Neutral', 'Agree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Strongly agree', 'Disagree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Agree', 'Data Analytics; Business Analytics', 'Business Analytics; Power BI', 'Self-Learning', 'Satisfied', 'Need more guidance on unfamiliar technical tasks.', 'Increase mentor guidance and technical review sessions.'),
('R076', '26–30 years', 'Female', 'Employee', 'Data Analytics', '6–12 months', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Disagree', 'Strongly agree', 'Agree', 'Neutral', 'Neutral', 'Disagree', 'Disagree', 'Agree', 'Disagree', 'Neutral', 'Neutral', 'Power BI; SQL; Python', 'SQL; Business Analytics', 'Live Projects', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Offer regular sessions on new technologies.'),
('R077', '20–25 years', 'Prefer not to say', 'Employee', 'Data Analytics', '3–6 months', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Business Analytics; Python', 'Power BI; Python; Data Analytics', 'Online Courses', 'Dissatisfied', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.'),
('R078', '26–30 years', 'Male', 'Employee', 'Mobile App Development', 'More than 1 year', 'Agree', 'Disagree', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Java; JavaScript', 'SQL; Java; Business Analytics', 'Live Projects', 'Neutral', 'Some tools are difficult without practical examples.', 'Create structured learning paths for each department.'),
('R079', 'Above 30 years', 'Male', 'Team Leader', 'Data Analytics', '6–12 months', 'Disagree', 'Disagree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Strongly agree', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Neutral', 'Disagree', 'Power BI; Business Analytics', 'Data Analytics; Python', 'Mentor Guidance', 'Neutral', 'Some tools are difficult without practical examples.', 'Provide more hands-on projects and practical workshops.'),
('R080', 'Above 30 years', 'Male', 'Employee', 'Data Analytics', 'More than 1 year', 'Disagree', 'Disagree', 'Strongly disagree', 'Disagree', 'Strongly disagree', 'Strongly disagree', 'Strongly agree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Power BI; Business Analytics; Data Analytics', 'Python; Data Analytics', 'Mentor Guidance', 'Very satisfied', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.');

-- INSERT RECORDS 81 TO 100
INSERT INTO Wahy_Employee_Skill_Gap (`Respondent_ID`, `Age`, `Gender`, `Designation`, `Department`, `Association_with_Wahy`, `Q6_Technical_skills_required`, `Q7_Adapt_to_new_technologies`, `Q8_Adequate_technical_training`, `Q9_Mentor_technical_guidance`, `Q10_Opportunities_to_improve_skills`, `Q11_Confidence_using_software_tools`, `Q12_Need_additional_technical_training`, `Q13_Training_applies_knowledge_to_real_projects`, `Q14_Complete_tasks_on_time`, `Q15_Work_quality_meets_expectations`, `Q16_Solve_technical_problems_independently`, `Q17_Collaborate_effectively`, `Q18_Adapt_to_project_changes`, `Q19_Technical_skills_influence_performance`, `Q20_Training_improved_performance`, `Q21_Satisfaction_with_work_performance`, `Q22_Current_technologies`, `Q23_Additional_training_needed`, `Q24_Most_effective_learning_method`, `Q25_Satisfaction_with_Wahy_training`, `Q26_Challenges`, `Q27_Suggestions`) VALUES
('R081', '20–25 years', 'Male', 'Employee', 'Data Analytics', '6–12 months', 'Agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Agree', 'Strongly agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Data Analytics; Power BI', 'Business Analytics; Data Analytics', 'Mentor Guidance', 'Neutral', 'Limited time to learn new technologies alongside assigned work.', 'Provide more real-world project exposure.'),
('R082', '20–25 years', 'Male', 'Employee', 'Mobile App Development', '3–6 months', 'Neutral', 'Strongly agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Disagree', 'Agree', 'Disagree', 'Strongly agree', 'Strongly agree', 'Agree', 'Agree', 'Flutter; SQL; Java', 'Java; SQL; Power BI', 'Live Projects', 'Very dissatisfied', 'Keeping up with multiple technologies is challenging.', 'Increase mentor guidance and technical review sessions.'),
('R083', '20–25 years', 'Female', 'Employee', 'Data Analytics', 'More than 1 year', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Data Analytics; Python', 'SQL; Business Analytics', 'Mentor Guidance', 'Very dissatisfied', 'More real-project exposure would improve confidence.', 'Offer regular sessions on new technologies.'),
('R084', '26–30 years', 'Male', 'Employee', 'Business Analytics', '6–12 months', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Disagree', 'Strongly agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Disagree', 'Power BI; Python; Business Analytics', 'Business Analytics; SQL; Data Analytics', 'Live Projects', 'Satisfied', 'Some tools are difficult without practical examples.', 'Provide more real-world project exposure.'),
('R085', '26–30 years', 'Male', 'Employee', 'Human Resources', 'Less than 3 months', 'Neutral', 'Neutral', 'Agree', 'Disagree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Data Analytics; Python; Business Analytics', 'Python; Business Analytics', 'Self-Learning', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more hands-on projects and practical workshops.'),
('R086', 'Above 30 years', 'Male', 'Team Leader', 'Data Analytics', 'More than 1 year', 'Neutral', 'Agree', 'Neutral', 'Disagree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Power BI; Business Analytics; SQL', 'Python; Power BI; Data Analytics', 'Classroom Training', 'Neutral', 'Need more hands-on practice with new tools.', 'Provide more hands-on projects and practical workshops.'),
('R087', '20–25 years', 'Male', 'Team Leader', 'Software Testing', 'More than 1 year', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Agree', 'Strongly agree', 'Agree', 'Software Testing; Python', 'Java; Software Testing; SQL', 'Self-Learning', 'Dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more hands-on projects and practical workshops.'),
('R088', '26–30 years', 'Female', 'Employee', 'Business Analytics', 'More than 1 year', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Disagree', 'Strongly agree', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Power BI; SQL', 'SQL; Power BI; Business Analytics', 'Live Projects', 'Very dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Offer regular sessions on new technologies.'),
('R089', '20–25 years', 'Female', 'Manager', 'Digital Marketing', 'More than 1 year', 'Strongly agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Data Analytics; Digital Marketing', 'Power BI; Business Analytics; Python', 'Classroom Training', 'Very dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Conduct short training sessions on required tools.'),
('R090', '26–30 years', 'Female', 'Team Leader', 'Data Analytics', '6–12 months', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Python; Power BI', 'SQL; Python', 'Self-Learning', 'Very dissatisfied', 'Need more guidance on unfamiliar technical tasks.', 'Provide more real-world project exposure.'),
('R091', '20–25 years', 'Female', 'Employee', 'Business Analytics', 'More than 1 year', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Strongly agree', 'Agree', 'Power BI; Data Analytics', 'SQL; Business Analytics', 'Online Courses', 'Dissatisfied', 'Need more hands-on practice with new tools.', 'Provide more hands-on projects and practical workshops.'),
('R092', 'Above 30 years', 'Male', 'Employee', 'Software Testing', '6–12 months', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Python; Java', 'Software Testing; Power BI; Business Analytics', 'Self-Learning', 'Neutral', 'Need more guidance on unfamiliar technical tasks.', 'Create structured learning paths for each department.'),
('R093', '20–25 years', 'Male', 'Employee', 'Mobile App Development', 'Less than 3 months', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Java; Flutter', 'Power BI; Python; Flutter', 'Classroom Training', 'Neutral', 'Keeping up with multiple technologies is challenging.', 'Offer regular sessions on new technologies.'),
('R094', '26–30 years', 'Male', 'Team Leader', 'Data Analytics', 'More than 1 year', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Agree', 'Neutral', 'Agree', 'Agree', 'Strongly agree', 'SQL; Power BI', 'Power BI; Data Analytics', 'Classroom Training', 'Very dissatisfied', 'More real-project exposure would improve confidence.', 'Provide more hands-on projects and practical workshops.'),
('R095', '20–25 years', 'Male', 'Employee', 'Human Resources', 'More than 1 year', 'Agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Neutral', 'Strongly agree', 'Disagree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Neutral', 'Business Analytics; Data Analytics', 'Power BI; Business Analytics', 'Classroom Training', 'Very dissatisfied', 'Some tools are difficult without practical examples.', 'Increase mentor guidance and technical review sessions.'),
('R096', '20–25 years', 'Prefer not to say', 'Employee', 'Business Analytics', 'More than 1 year', 'Strongly agree', 'Agree', 'Agree', 'Agree', 'Strongly agree', 'Strongly agree', 'Neutral', 'Strongly agree', 'Strongly agree', 'Strongly agree', 'Agree', 'Agree', 'Neutral', 'Strongly agree', 'Agree', 'Agree', 'Data Analytics; Power BI', 'Data Analytics; SQL', 'Live Projects', 'Very dissatisfied', 'Need more hands-on practice with new tools.', 'Conduct short training sessions on required tools.'),
('R097', 'Above 30 years', 'Male', 'Employee', 'Business Analytics', '6–12 months', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Agree', 'Neutral', 'Business Analytics; Python; SQL', 'SQL; Data Analytics', 'Online Courses', 'Satisfied', 'More real-project exposure would improve confidence.', 'Create structured learning paths for each department.'),
('R098', '26–30 years', 'Male', 'Employee', 'Data Analytics', 'More than 1 year', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Power BI; Python; Data Analytics', 'Python; SQL', 'Classroom Training', 'Neutral', 'Need more hands-on practice with new tools.', 'Offer regular sessions on new technologies.'),
('R099', '26–30 years', 'Female', 'Team Leader', 'Data Analytics', '3–6 months', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Strongly agree', 'Disagree', 'Agree', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Agree', 'Python; Business Analytics', 'SQL; Data Analytics', 'Online Courses', 'Neutral', 'Need more hands-on practice with new tools.', 'Offer regular sessions on new technologies.'),
('R100', '26–30 years', 'Male', 'Employee', 'Mobile App Development', '6–12 months', 'Neutral', 'Agree', 'Agree', 'Disagree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Agree', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Flutter; Java', 'Data Analytics; SQL; JavaScript', 'Self-Learning', 'Neutral', 'Keeping up with multiple technologies is challenging.', 'Provide more real-world project exposure.');

-- BASIC ANALYSIS QUERIES
SELECT COUNT(*) AS Total_Respondents FROM Wahy_Employee_Skill_Gap;
SELECT Gender, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Gender;
SELECT Designation, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Designation;
SELECT Department, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Department ORDER BY No_of_Respondents DESC;
SELECT Age, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Age ORDER BY Age;
SELECT Q7_Adapt_to_new_technologies, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Q7_Adapt_to_new_technologies;
SELECT Q8_Adequate_technical_training, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Q8_Adequate_technical_training;
SELECT Q9_Mentor_technical_guidance, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Q9_Mentor_technical_guidance;
SELECT Q11_Confidence_using_software_tools, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Q11_Confidence_using_software_tools;
SELECT Q12_Need_additional_technical_training, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Q12_Need_additional_technical_training;
SELECT Q24_Most_effective_learning_method, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Q24_Most_effective_learning_method;
SELECT Q25_Satisfaction_with_Wahy_training, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Q25_Satisfaction_with_Wahy_training;
-- EMPLOYEE / INTERN GROUPING (Intern only = Intern; all other designations = Employee)
SELECT CASE WHEN Designation='Intern' THEN 'Intern' ELSE 'Employee' END AS Employee_Status, COUNT(*) AS No_of_Respondents FROM Wahy_Employee_Skill_Gap GROUP BY Employee_Status;
-- TECHNOLOGICAL SKILL SCORE
SELECT Respondent_ID,
ROUND((CASE Q6_Technical_skills_required WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
CASE Q7_Adapt_to_new_technologies WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
CASE Q11_Confidence_using_software_tools WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END)/3,2) AS Technological_Skill_Score
FROM Wahy_Employee_Skill_Gap;
-- OVERALL TECHNOLOGICAL SKILL MEAN
SELECT ROUND(AVG((
CASE Q6_Technical_skills_required WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
CASE Q7_Adapt_to_new_technologies WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
CASE Q11_Confidence_using_software_tools WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END)/3),2) AS Technological_Skill_Mean
FROM Wahy_Employee_Skill_Gap;
-- TRAINING/SUPPORT MEAN (Q12 reverse-coded: 6 - original score)
SELECT ROUND(AVG((
CASE Q8_Adequate_technical_training WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
CASE Q9_Mentor_technical_guidance WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
CASE Q10_Opportunities_to_improve_skills WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
(6-CASE Q12_Need_additional_technical_training WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END) +
CASE Q13_Training_applies_knowledge_to_real_projects WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END +
CASE Q20_Training_improved_performance WHEN 'Strongly disagree' THEN 1 WHEN 'Disagree' THEN 2 WHEN 'Neutral' THEN 3 WHEN 'Agree' THEN 4 WHEN 'Strongly agree' THEN 5 END)/6),2) AS Training_Support_Mean
FROM Wahy_Employee_Skill_Gap;